-- [1] Consulta para saber o tamanho e integridade de cada tabela do dataset
SELECT
	(
		SELECT
			COUNT(CUSTOMER_ID)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_CUSTOMERS
	) AS REGISTROS_CLIENTES,
	(
		SELECT
			COUNT(PRODUCT_ID)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_PRODUCTS
	) AS REGISTROS_PRODUTOS,
	(
		SELECT
			COUNT(SELLER_ID)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_SELLERS
	) AS REGISTROS_VENDEDORES,
	(
		SELECT
			COUNT(ORDER_ID)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_ORDERS
	) AS REGISTROS_PEDIDOS,
	(
		SELECT
			COUNT(ORDER_ITEM_ID)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS
	) AS REGISTROS_PEDIDOS_ITENS,
	(
		SELECT
			COUNT(GEOLOCATION_ZIP_CODE_PREFIX)
		FROM
			OLIST_PUBLIC_DATASET.OLIST_GEOLOCATION
	) AS REGISTROS_GEOLOCALIZACAO;

-- [2] Consulta para saber o pedido com maior e menor valor
WITH
	PEDIDOS AS (
		SELECT
			ORD.ORDER_ID,
			ROUND(SUM(ORI.PRICE + ORI.FREIGHT_VALUE), 2) AS VALOR_VENDA
		FROM
			OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
			JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
		GROUP BY
			ORD.ORDER_ID
	)
SELECT
	MAX(VALOR_VENDA)::MONEY AS MAIOR_VALOR_VENDA,
	MIN(VALOR_VENDA)::MONEY AS MENOR_VALOR_VENDA
FROM
	PEDIDOS;

-- [3] Consulta para ter o total de pedidos e valor total vendido
SELECT
	COUNT(DISTINCT ORD.ORDER_ID) AS TOTAL_PEDIDOS,
	SUM(ORI.PRICE + ORI.FREIGHT_VALUE)::MONEY AS RECEITA_TOTAL
FROM
	OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
	JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID;
