-- [8] Quantidade de pedidos por categoria
SELECT
	PRO.PRODUCT_CATEGORY_NAME,
	COUNT(ORI.ORDER_ID) AS QTD_PEDIDOS
FROM
	OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
	JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
	JOIN OLIST_PUBLIC_DATASET.OLIST_PRODUCTS AS PRO ON ORI.PRODUCT_ID = PRO.PRODUCT_ID
GROUP BY
	PRO.PRODUCT_CATEGORY_NAME
ORDER BY
	QTD_PEDIDOS DESC;

-- [9] Valor total de venda por categoria
SELECT
	PRO.PRODUCT_CATEGORY_NAME,
	ROUND(SUM(ORI.PRICE + ORI.FREIGHT_VALUE), 2)::MONEY AS VALOR_VENDA
FROM
	OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
	JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
	JOIN OLIST_PUBLIC_DATASET.OLIST_PRODUCTS AS PRO ON ORI.PRODUCT_ID = PRO.PRODUCT_ID
GROUP BY
	PRO.PRODUCT_CATEGORY_NAME
ORDER BY
	VALOR_VENDA DESC;

