-- [10] Quantidade de clientes por estado
SELECT
	CUSTOMER_STATE,
	COUNT(CUSTOMER_ID) AS QTD_CLIENTES
FROM
	OLIST_PUBLIC_DATASET.OLIST_CUSTOMERS
GROUP BY
	CUSTOMER_STATE
ORDER BY
	QTD_CLIENTES DESC;

-- [11] Ranking de quantidade de clientes de cada cidade dentro de cada estado
SELECT
	CUSTOMER_STATE,
	CUSTOMER_CITY,
	COUNT(CUSTOMER_ID) AS QTD_CLIENTES,
	DENSE_RANK() OVER (
		PARTITION BY
			CUSTOMER_STATE
		ORDER BY
			COUNT(CUSTOMER_ID) DESC
	) AS RANK_CIDADE
FROM
	OLIST_PUBLIC_DATASET.OLIST_CUSTOMERS
GROUP BY
	CUSTOMER_STATE,
	CUSTOMER_CITY
ORDER BY
	CUSTOMER_STATE,
	RANK_CIDADE;