-- [4] Consulta para ter o ticket médio por pedido
WITH
	PEDIDOS AS (
		SELECT
			ORD.ORDER_ID,
			SUM(ORI.PRICE + ORI.FREIGHT_VALUE) AS TOTAL_PEDIDO
		FROM
			OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
			JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
		GROUP BY
			ORD.ORDER_ID
	)
SELECT
	ROUND(AVG(TOTAL_PEDIDO), 2)::MONEY AS TICKET_MEDIO
FROM
	PEDIDOS;

-- [5] Consulta para ter a receita e ticket médio por mês do ano de 2017
SELECT
	TO_CHAR(ORD.ORDER_PURCHASE_TIMESTAMP, 'Month') AS MES,
	SUM(ORI.PRICE + ORI.FREIGHT_VALUE)::MONEY AS TOTAL_PEDIDO,
	ROUND(AVG(ORI.PRICE + ORI.FREIGHT_VALUE), 2)::MONEY AS TICKET_MEDIO
FROM
	OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
	JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
WHERE
	EXTRACT(
		YEAR
		FROM
			ORD.ORDER_PURCHASE_TIMESTAMP
	) = '2017'
GROUP BY
	MES,
	EXTRACT(
		MONTH
		FROM
			ORD.ORDER_PURCHASE_TIMESTAMP
	)
ORDER BY
	EXTRACT(
		MONTH
		FROM
			ORD.ORDER_PURCHASE_TIMESTAMP
	);

-- [6] Consulta para ter a quantidade de pedidos por mês e ordernado pelo valor total
SELECT
	CASE
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 1 THEN 'Janeiro'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 2 THEN 'Fevereiro'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 3 THEN 'Março'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 4 THEN 'Abril'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 5 THEN 'Maio'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 6 THEN 'Junho'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 7 THEN 'Julho'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 8 THEN 'Agosto'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 9 THEN 'Setembro'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 10 THEN 'Outubro'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 11 THEN 'Novembro'
		WHEN EXTRACT(
			MONTH
			FROM
				ORD.ORDER_PURCHASE_TIMESTAMP
		) = 12 THEN 'Dezembro'
	END AS MES,
	ROUND(SUM(ORI.PRICE + ORI.FREIGHT_VALUE), 2) AS VALOR_TOTAL
FROM
	OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
	JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
GROUP BY
	MES
ORDER BY
	VALOR_TOTAL DESC;

-- [7] Consulta para ter a quantidade de venda por mês do ano de 2017 e mostrar o crescimento das vendas mensais
-- em relação ao mês anterior
WITH
	VENDAS_MENSAIS_2017 AS (
		SELECT
			EXTRACT(
				MONTH
				FROM
					ORD.ORDER_PURCHASE_TIMESTAMP
			) AS MES,
			ROUND(SUM(ORI.PRICE + ORI.FREIGHT_VALUE), 2) AS VALOR_TOTAL
		FROM
			OLIST_PUBLIC_DATASET.OLIST_ORDERS AS ORD
			JOIN OLIST_PUBLIC_DATASET.OLIST_ORDER_ITEMS AS ORI ON ORD.ORDER_ID = ORI.ORDER_ID
		WHERE
			EXTRACT(
				YEAR
				FROM
					ORD.ORDER_PURCHASE_TIMESTAMP
			) = '2017'
		GROUP BY
			MES
		ORDER BY
			MES
	)
SELECT
	CASE
		WHEN MES = 1 THEN 'Janeiro'
		WHEN MES = 2 THEN 'Feveiro'
		WHEN MES = 3 THEN 'Março'
		WHEN MES = 4 THEN 'Abril'
		WHEN MES = 5 THEN 'Maio'
		WHEN MES = 6 THEN 'Junho'
		WHEN MES = 7 THEN 'Julho'
		WHEN MES = 8 THEN 'Agosto'
		WHEN MES = 9 THEN 'Setembro'
		WHEN MES = 10 THEN 'Outubro'
		WHEN MES = 11 THEN 'Novembro'
		WHEN MES = 12 THEN 'Dezembro'
	END AS MES,
	VALOR_TOTAL::MONEY,
	COALESCE(
		VALOR_TOTAL - LAG(VALOR_TOTAL) OVER (
			ORDER BY
				MES
		),
		0
	)::MONEY AS VARIACAO_MES_ANTERIOR,
	CONCAT(
		COALESCE(
			ROUND(
				(
					(
						VALOR_TOTAL - LAG(VALOR_TOTAL) OVER (
							ORDER BY
								MES
						)
					) * 100 / (
						LAG(VALOR_TOTAL) OVER (
							ORDER BY
								MES
						)
					)
				),
				1
			),
			0
		),
		' %'
	) AS "variacao_em_%"
FROM
	VENDAS_MENSAIS_2017;

  